# Generated by Django 5.0 on 2023-12-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('f_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=100)),
                ('fumador', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('transito_intestinal', models.BooleanField(default=False)),
                ('hidratacion', models.CharField(choices=[('Más de 1,5 litros diarios', 'Más de 1,5 litros diarios'), ('Menos de 1,5 litros diarios', 'Menos de 1,5 litros diarios')], max_length=100)),
                ('alergias', models.TextField()),
                ('tratamientos', models.TextField()),
                ('habitos', models.TextField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
