# Generated by Django 5.0 on 2023-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='transito_intestinal',
            new_name='transito_intestinal_normal',
        ),
        migrations.AddField(
            model_name='client',
            name='f_inicio',
            field=models.DateField(default=None),
        ),
    ]
