# Generated by Django 5.0 on 2023-12-22 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_rename_habitos_cliente_habitos_alimenticios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azucar', models.FloatField()),
                ('tiroides', models.FloatField()),
                ('acido_urico', models.FloatField()),
                ('anemia', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='diets.cliente')),
            ],
        ),
    ]
