# Generated by Django 5.0 on 2023-12-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_analitica'),
    ]

    operations = [
        migrations.AddField(
            model_name='analitica',
            name='fecha',
            field=models.DateField(default=None),
        ),
    ]
