# Generated by Django 5.0 on 2023-12-23 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0005_analitica_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='analitica',
            name='cliente',
        ),
        migrations.AddField(
            model_name='analitica',
            name='cliente_analitica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente_analitica', to='diets.cliente'),
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comida', models.CharField(max_length=100)),
                ('categoria_comida', models.ManyToManyField(blank=True, related_name='categoria_comida', to='diets.categoria_comida')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('contorno_cintura', models.FloatField()),
                ('contorno_cadera', models.FloatField()),
                ('grasa_corporal', models.FloatField()),
                ('IMC', models.FloatField()),
                ('cliente_revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_revision', to='diets.cliente')),
            ],
        ),
    ]
