# Generated by Django 5.0 on 2023-12-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0006_categoria_comida_remove_analitica_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analitica',
            old_name='cliente_analitica',
            new_name='cliente',
        ),
    ]
