# Generated by Django 5.0 on 2023-12-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0008_remove_comida_categoria_comida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desayuno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision', to='diets.datos_revision')),
            ],
        ),
    ]
