# Generated by Django 5.0 on 2023-12-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_desayuno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_revision',
            old_name='cliente_revision',
            new_name='cliente',
        ),
    ]
