# Generated by Django 5.0 on 2023-12-23 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_rename_cliente_revision_datos_revision_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desayuno',
            name='platos',
            field=models.ManyToManyField(blank=True, related_name='platos_desayuno', to='diets.comida'),
        ),
        migrations.AlterField(
            model_name='desayuno',
            name='revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_desayuno', to='diets.datos_revision'),
        ),
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos_almuerzo', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_almuerzo', to='diets.datos_revision')),
            ],
        ),
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos_cena', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_cena', to='diets.datos_revision')),
            ],
        ),
        migrations.CreateModel(
            name='Media_manana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos_media_manana', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_media_manana', to='diets.datos_revision')),
            ],
        ),
        migrations.CreateModel(
            name='Merienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos_merienda', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_merienda', to='diets.datos_revision')),
            ],
        ),
        migrations.CreateModel(
            name='Post_cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platos', models.ManyToManyField(blank=True, related_name='platos_post_cena', to='diets.comida')),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_post_cena', to='diets.datos_revision')),
            ],
        ),
    ]
