# Generated by Django 5.0 on 2023-12-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_alter_cliente_alergias_alter_cliente_habitos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='habitos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tratamientos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
