# Generated by Django 5.0 on 2023-12-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0013_alter_cliente_alergias_alter_cliente_habitos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cena',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='cena',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='media_manana',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='media_manana',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='merienda',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='merienda',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='post_cena',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='post_cena',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='desayuno',
            name='platos',
        ),
        migrations.DeleteModel(
            name='Almuerzo',
        ),
        migrations.DeleteModel(
            name='Cena',
        ),
        migrations.DeleteModel(
            name='Media_manana',
        ),
        migrations.DeleteModel(
            name='Merienda',
        ),
        migrations.DeleteModel(
            name='Post_cena',
        ),
        migrations.AddField(
            model_name='desayuno',
            name='platos',
            field=models.JSONField(default=[]),
        ),
    ]
