# Generated by Django 5.0 on 2023-12-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0014_remove_cena_platos_remove_cena_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desayuno',
            name='platos',
            field=models.JSONField(default=list),
        ),
    ]
