# Generated by Django 5.0 on 2023-12-27 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0015_alter_desayuno_platos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desayuno', models.JSONField(default=list)),
                ('media_manana', models.JSONField(default=list)),
                ('almuerzo', models.JSONField(default=list)),
                ('merienda', models.JSONField(default=list)),
                ('cena', models.JSONField(default=list)),
                ('post_cena', models.JSONField(default=list)),
                ('revision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_desayuno', to='diets.datos_revision')),
            ],
        ),
        migrations.DeleteModel(
            name='Desayuno',
        ),
    ]
