# Generated by Django 5.0 on 2023-12-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0016_dieta_delete_desayuno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_revision',
            name='altura',
        ),
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='almuerzo',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='cena',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='desayuno',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='media_manana',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='merienda',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='datos_revision',
            name='post_cena',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='IMC',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='contorno_cadera',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='contorno_cintura',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='grasa_corporal',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='peso',
            field=models.FloatField(default=None),
        ),
        migrations.DeleteModel(
            name='Dieta',
        ),
    ]
