# Generated by Django 5.0 on 2023-12-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0017_remove_datos_revision_altura_cliente_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_revision',
            name='IMC',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='contorno_cadera',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='contorno_cintura',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='grasa_corporal',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='peso',
            field=models.FloatField(default=None, null=True),
        ),
    ]
