# Generated by Django 5.0 on 2023-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0019_alter_datos_revision_imc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_revision',
            name='fecha',
            field=models.DateField(default=None, null=True),
        ),
    ]
