# Generated by Django 5.0 on 2023-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0020_alter_datos_revision_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_revision',
            name='fecha_proxima',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
