# Generated by Django 5.0 on 2024-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0022_alter_datos_revision_almuerzo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_revision',
            name='almuerzo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='cena',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='desayuno',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='media_manana',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='merienda',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datos_revision',
            name='post_cena',
            field=models.TextField(blank=True, null=True),
        ),
    ]
