# Generated by Django 5.0 on 2024-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0023_alter_datos_revision_almuerzo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_revision',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
